### ISSUE TITLE
Could not call method 'public static org.bukkit.inventory.meta.ItemMeta 

### ISSUE THREAD

**Issue by GenifeG** [WiIIiam278/HuskSync#122]
Sometimes this happens to some players. The version from github also does not solve the problem

```java
[18:20:16] [ForkJoinPool.commonPool-worker-22/INFO]: [HuskSync] [DEBUG] [RU_Hed_Red] Could not read SERVER_SWITCH key from redis at: 20:16.144
[18:20:16] [ForkJoinPool.commonPool-worker-16/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:38) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaSkull.setOwnerProfile(CraftMetaSkull.java:265) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:93) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at jdk.internal.reflect.GeneratedConstructorAccessor230.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:202) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1784) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:509) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:467) ~[?:?]
	at java.util.HashMap.readObject(HashMap.java:1552) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:509) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:467) ~[?:?]
	at net.william278.husksync.data.BukkitSerializer.lambda$deserializeItemStackArray$2(BukkitSerializer.java:99) ~[HuskSync-Bukkit-2.2.4-7ed7d0a.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1253) ~[?:?]
	at java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2237) ~[?:?]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887) ~[?:?]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117) ~[?:?]
	at net.william278.husksync.data.BukkitSerializer.lambda$deserializeInventory$1(BukkitSerializer.java:70) ~[HuskSync-Bukkit-2.2.4-7ed7d0a.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[18:20:16] [ForkJoinPool.commonPool-worker-16/ERROR]: [HuskSync] Failed to deserialize item stack data
java.io.IOException: Failed to deserialize object
	at org.bukkit.util.io.BukkitObjectInputStream.newIOException(BukkitObjectInputStream.java:59) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:51) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1784) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:509) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:467) ~[?:?]
	at java.util.HashMap.readObject(HashMap.java:1552) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257) ~[?:?]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:509) ~[?:?]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:467) ~[?:?]
	at net.william278.husksync.data.BukkitSerializer.lambda$deserializeItemStackArray$2(BukkitSerializer.java:99) ~[HuskSync-Bukkit-2.2.4-7ed7d0a.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1253) ~[?:?]
	at java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2237) ~[?:?]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887) ~[?:?]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117) ~[?:?]
	at net.william278.husksync.data.BukkitSerializer.lambda$deserializeInventory$1(BukkitSerializer.java:70) ~[HuskSync-Bukkit-2.2.4-7ed7d0a.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(java.util.Map)" is null
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 30 more
[18:20:16] [ForkJoinPool.commonPool-worker-17/ERROR]: [HuskSync] Failed to set data for player RU_Hed_Red (net.william278.husksync.data.DataSerializationException: Failed to deserialize item stack data)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: java.util.concurrent.CompletionException: net.william278.husksync.data.DataSerializationException: Failed to deserialize item stack data
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1253)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2237)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at HuskSync-Bukkit-2.2.4-7ed7d0a.jar//net.william278.husksync.data.BukkitSerializer.lambda$deserializeInventory$1(BukkitSerializer.java:70)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: Caused by: net.william278.husksync.data.DataSerializationException: Failed to deserialize item stack data
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at HuskSync-Bukkit-2.2.4-7ed7d0a.jar//net.william278.husksync.data.BukkitSerializer.lambda$deserializeItemStackArray$2(BukkitSerializer.java:112)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	... 14 more
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: Caused by: java.io.IOException: Failed to deserialize object
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at org.bukkit.util.io.BukkitObjectInputStream.newIOException(BukkitObjectInputStream.java:59)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:51)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1784)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.util.HashMap.readObject(HashMap.java:1552)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1100)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2423)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at HuskSync-Bukkit-2.2.4-7ed7d0a.jar//net.william278.husksync.data.BukkitSerializer.lambda$deserializeItemStackArray$2(BukkitSerializer.java:99)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	... 15 more
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(java.util.Map)" is null
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49)
[18:20:16] [ForkJoinPool.commonPool-worker-17/WARN]: 	... 30 more
```

**Comment by WiIIiam278** [comment]
Please open a ticket on Discord and provide proof of purchase for support :)
