### ISSUE TITLE
sometimes fails to dump playerdata to db 

### ISSUE THREAD

**Issue by aaa8881** [WiIIiam278/HuskSync#123]
```
[12:57:28] [ForkJoinPool.commonPool-worker-12/INFO]: [HuskSync] [DEBUG] [Kim_RaKun] Set SERVER_SWITCH key to redis at: 57:28.595
[12:57:28] [ForkJoinPool.commonPool-worker-8/ERROR]: [HuskSync] Failed to get user data from online player Kim_RaKun (java.util.ConcurrentModificationException)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: Caused by: java.util.ConcurrentModificationException
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftLivingEntity.getActivePotionEffects(CraftLivingEntity.java:490)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at HuskSync-2.2.4.jar//net.william278.husksync.player.BukkitPlayer.getPotionEffects(BukkitPlayer.java:197)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at HuskSync-2.2.4.jar//net.william278.husksync.player.OnlineUser$2.<init>(OnlineUser.java:340)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at HuskSync-2.2.4.jar//net.william278.husksync.player.OnlineUser.lambda$getUserData$3(OnlineUser.java:324)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[12:57:28] [ForkJoinPool.commonPool-worker-8/WARN]: 	... 6 more
```

**Comment by WiIIiam278** [comment]
Join discord for support :)
