### ISSUE TITLE
java.util.ConcurrentModificationException in HuskSync 2.2.8

### ISSUE THREAD

**Issue by Florianpal1** [WiIIiam278/HuskSync#154]
I have this error in HuskSync 2.2.8 and causes equipment loss

[15:19:13 WARN]: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
[15:19:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[15:19:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[15:19:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[15:19:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[15:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[15:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[15:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[15:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[15:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[15:19:13 WARN]: Caused by: java.util.ConcurrentModificationException
[15:19:13 WARN]:        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[15:19:13 WARN]:        at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
[15:19:13 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftLivingEntity.getActivePotionEffects(CraftLivingEntity.java:500)
[15:19:13 WARN]:        at HuskSync-2.2.8.jar//net.william278.husksync.player.BukkitPlayer.getPotionEffects(BukkitPlayer.java:226)
[15:19:13 WARN]:        at HuskSync-2.2.8.jar//net.william278.husksync.player.OnlineUser$2.<init>(OnlineUser.java:383)
[15:19:13 WARN]:        at HuskSync-2.2.8.jar//net.william278.husksync.player.OnlineUser.lambda$getUserData$3(OnlineUser.java:367)
[15:19:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:19:13 WARN]:        ... 6 more

**Comment by WiIIiam278** [comment]
Please join Discord and verify your purchase so we can diagnose this further :)
