### ISSUE TITLE
Maximum health value fails to synchronize properly

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#2]
```
[18:39:37 WARN]: [HuskSync] Task #41 for HuskSync v1.0.2 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 49.75. (attribute base value: 20.0, player: [redacted])
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:110) ~[patched_1.17.1.jar:git-Purpur-1260]
        at me.william278.husksync.bukkit.util.PlayerSetter.lambda$setPlayerFrom$0(PlayerSetter.java:154) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1260]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1260]
        at java.lang.Thread.run(Thread.java:831) [?:?]

```

**Comment by WiIIiam278** [comment]
Still doesn't appear to be fixed; error is not being thrown anymore but now player max health is continuously increasing in some circumstances. Additional checks required
![image](https://user-images.githubusercontent.com/31187453/139542300-7ad6dff3-ef7d-4c27-9c57-bc59ca8eff7d.png)
