### ISSUE TITLE
Inventory synchronization problem. Desyncs inventories

### ISSUE THREAD

**Issue by LimbaSau** [WiIIiam278/HuskSync#259]
[17:10:36 WARN]: [net.william278.husksync.libraries.hikari.pool.PoolBase] HuskSyncHikariPool - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@42c2b562 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[17:10:36 ERROR]: [HuskSync] Failed to delete a user's data from the database
java.sql.SQLTransientConnectionException: HuskSyncHikariPool - Connection is not available, request timed out after 5004ms (total=9, active=0, idle=9, waiting=0)
        at net.william278.husksync.libraries.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.libraries.hikari.pool.HikariPool.getConnection(HikariPool.java:179) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.libraries.hikari.pool.HikariPool.getConnection(HikariPool.java:144) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.libraries.hikari.HikariDataSource.getConnection(HikariDataSource.java:127) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.database.MySqlDatabase.getConnection(MySqlDatabase.java:67) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.database.MySqlDatabase.rotateLatestSnapshot(MySqlDatabase.java:355) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.database.Database.addSnapshot(Database.java:178) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.sync.DataSyncer.addSnapshotToDatabase(DataSyncer.java:142) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.sync.DataSyncer.lambda$saveData$0(DataSyncer.java:118) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.event.EventDispatcher.lambda$fireEvent$0(EventDispatcher.java:46) ~[HuskSync-3.4.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2457) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at net.william278.husksync.libraries.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:562) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.libraries.hikari.pool.PoolBase.isConnectionDead(PoolBase.java:169) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.libraries.hikari.pool.HikariPool.getConnection(HikariPool.java:168) ~[HuskSync-3.4.jar:?]
        ... 14 more
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:753) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:565) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2453) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at net.william278.husksync.libraries.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:562) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.libraries.hikari.pool.PoolBase.isConnectionDead(PoolBase.java:169) ~[HuskSync-3.4.jar:?]
        at net.william278.husksync.libraries.hikari.pool.HikariPool.getConnection(HikariPool.java:168) ~[HuskSync-3.4.jar:?]
        ... 14 more

**Comment by WiIIiam278** [comment]
Please get in touch with us on Discord for support issues.
