### ISSUE TITLE
Failed to initialize Redis server connection

### ISSUE THREAD

**Issue by ch4ika** [WiIIiam278/HuskSync#320]
I wanted to try out the latest version of HuskSync 3.6 today and also updated to the current Redis version today. If that's anything relevant here, I wanted to report it.

Older version of HuskSync 3.5 works without problems.

```
[13:43:56] [Server thread/INFO]: [HuskSync] Enabling HuskSync v3.6-8936877
[13:43:56] [Server thread/INFO]: [HuskSync] Initializing data adapter...
[13:43:56] [Server thread/INFO]: [HuskSync] Successfully initialized data adapter
[13:43:56] [Server thread/INFO]: [HuskSync] Initializing data serializers...
[13:43:56] [Server thread/INFO]: [HuskSync] Successfully initialized data serializers
[13:43:56] [Server thread/INFO]: [HuskSync] Initializing data migrators/converters...
[13:43:56] [Server thread/INFO]: [HuskSync] Successfully initialized data migrators/converters
[13:43:56] [Server thread/INFO]: [HuskSync] Initializing MySQL database connection...
[13:43:56] [Server thread/INFO]: [net.william278.husksync.libraries.hikari.HikariDataSource] HuskSyncHikariPool - Starting...
[13:43:56] [Server thread/INFO]: [net.william278.husksync.libraries.hikari.pool.HikariPool] HuskSyncHikariPool - Added connection com.mysql.cj.jdbc.ConnectionImpl@794aa82d
[13:43:56] [Server thread/INFO]: [net.william278.husksync.libraries.hikari.HikariDataSource] HuskSyncHikariPool - Start completed.
[13:43:56] [Server thread/INFO]: [HuskSync] Successfully initialized MySQL database connection
[13:43:56] [Server thread/INFO]: [HuskSync] Initializing Redis server connection...
[13:43:56] [Server thread/ERROR]: Error occurred while enabling HuskSync v3.6-8936877 (Is it up to date?)
net.william278.husksync.HuskSync$FailedToLoadException: HuskSync has failed to load! The plugin will not be enabled and no data will be synchronized.
Please make sure the plugin has been setup correctly (https://william278.net/docs/husksync/setup):

1) Make sure you've entered your MySQL, MariaDB or MongoDB database details correctly in config.yml
2) Make sure your Redis server details are also correct in config.yml
3) Make sure your config is up-to-date (https://william278.net/docs/husksync/config-file)
4) Check the error below for more details

Caused by: Failed to initialize Redis server connection
	at net.william278.husksync.HuskSync.initialize(HuskSync.java:146) ~[HuskSync-Paper-3.6-8936877.jar:?]
	at net.william278.husksync.BukkitHuskSync.onEnable(BukkitHuskSync.java:185) ~[HuskSync-Paper-3.6-8936877.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/william278/husksync/redis/RedisManager.initialize()V @126: invokespecial
  Reason:
    Type 'redis/clients/jedis/JedisPoolConfig' (current frame, stack[3]) is not assignable to 'org/apache/commons/pool2/impl/GenericObjectPoolConfig'
  Current Frame:
    bci: @126
    flags: { }
    locals: { 'net/william278/husksync/redis/RedisManager', 'net/william278/husksync/config/Settings$RedisSettings$RedisCredentials', 'java/lang/String', 'java/lang/String', integer, integer, 'redis/clients/jedis/JedisPoolConfig', 'net/william278/husksync/config/Settings$RedisSettings$RedisSentinel', 'java/util/HashSet' }
    stack: { 'net/william278/husksync/redis/RedisManager', uninitialized 114, uninitialized 114, 'redis/clients/jedis/JedisPoolConfig', 'java/lang/String', integer, integer, integer }
  Bytecode:
    0000000: 2ab4 004a b900 5001 00b6 0067 b600 6b4c
    0000010: 2bb6 006e 4d2b b600 714e 2bb6 0075 3604
    0000020: 2bb6 0079 3605 bb00 7b59 b700 7c3a 0619
    0000030: 0603 b600 8019 0604 b600 8419 0604 b600
    0000040: 872a b400 4ab9 0050 0100 b600 67b6 008b
    0000050: 3a07 bb00 8d59 1907 b600 91b7 0094 3a08
    0000060: 1908 b900 9901 0099 0033 2a2c b600 9c99
    0000070: 0015 bb00 9e59 1906 2d15 0403 1505 b700
    0000080: a1a7 0013 bb00 9e59 1906 2d15 0403 2c15
    0000090: 05b7 00a4 b500 a8a7 0036 1907 b600 a93a
    00000a0: 092a bb00 ab59 1907 b600 ae19 082c b600
    00000b0: 9c99 0007 01a7 0004 2c19 09b6 009c 9900
    00000c0: 0701 a700 0519 09b7 00b1 b500 a82a b400
    00000d0: a8b6 00b5 c000 b7b6 00ba 57a7 0011 3a09
    00000e0: bb00 6059 12bc 1909 b700 bfbf 2a04 b500
    00000f0: c1bb 00c3 592a ba00 d300 0012 d5b7 00d8
    0000100: b600 dbb1                              
  Exception Handler Table:
    bci [205, 219] => handler: 222
  Stackmap Table:
    full_frame(@132,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150]},{Object[#2]})
    full_frame(@148,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150]},{Object[#2],Object[#166]})
    same_frame(@154)
    full_frame(@184,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150],Object[#155]},{Object[#2],Uninitialized[#162],Uninitialized[#162],Object[#155],Object[#150]})
    full_frame(@185,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150],Object[#155]},{Object[#2],Uninitialized[#162],Uninitialized[#162],Object[#155],Object[#150],Object[#155]})
    full_frame(@197,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150],Object[#155]},{Object[#2],Uninitialized[#162],Uninitialized[#162],Object[#155],Object[#150],Object[#155]})
    full_frame(@199,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150],Object[#155]},{Object[#2],Uninitialized[#162],Uninitialized[#162],Object[#155],Object[#150],Object[#155],Object[#155]})
    chop_frame(@205,1)
    same_locals_1_stack_item_frame(@222,Object[#99])
    same_frame(@236)

	at net.william278.husksync.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:45) ~[HuskSync-Paper-3.6-8936877.jar:?]
	at net.william278.husksync.HuskSync.initialize(HuskSync.java:144) ~[HuskSync-Paper-3.6-8936877.jar:?]
	... 13 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/william278/husksync/redis/RedisManager.initialize()V @126: invokespecial
  Reason:
    Type 'redis/clients/jedis/JedisPoolConfig' (current frame, stack[3]) is not assignable to 'org/apache/commons/pool2/impl/GenericObjectPoolConfig'
  Current Frame:
    bci: @126
    flags: { }
    locals: { 'net/william278/husksync/redis/RedisManager', 'net/william278/husksync/config/Settings$RedisSettings$RedisCredentials', 'java/lang/String', 'java/lang/String', integer, integer, 'redis/clients/jedis/JedisPoolConfig', 'net/william278/husksync/config/Settings$RedisSettings$RedisSentinel', 'java/util/HashSet' }
    stack: { 'net/william278/husksync/redis/RedisManager', uninitialized 114, uninitialized 114, 'redis/clients/jedis/JedisPoolConfig', 'java/lang/String', integer, integer, integer }
  Bytecode:
    0000000: 2ab4 004a b900 5001 00b6 0067 b600 6b4c
    0000010: 2bb6 006e 4d2b b600 714e 2bb6 0075 3604
    0000020: 2bb6 0079 3605 bb00 7b59 b700 7c3a 0619
    0000030: 0603 b600 8019 0604 b600 8419 0604 b600
    0000040: 872a b400 4ab9 0050 0100 b600 67b6 008b
    0000050: 3a07 bb00 8d59 1907 b600 91b7 0094 3a08
    0000060: 1908 b900 9901 0099 0033 2a2c b600 9c99
    0000070: 0015 bb00 9e59 1906 2d15 0403 1505 b700
    0000080: a1a7 0013 bb00 9e59 1906 2d15 0403 2c15
    0000090: 05b7 00a4 b500 a8a7 0036 1907 b600 a93a
    00000a0: 092a bb00 ab59 1907 b600 ae19 082c b600
    00000b0: 9c99 0007 01a7 0004 2c19 09b6 009c 9900
    00000c0: 0701 a700 0519 09b7 00b1 b500 a82a b400
    00000d0: a8b6 00b5 c000 b7b6 00ba 57a7 0011 3a09
    00000e0: bb00 6059 12bc 1909 b700 bfbf 2a04 b500
    00000f0: c1bb 00c3 592a ba00 d300 0012 d5b7 00d8
    0000100: b600 dbb1                              
  Exception Handler Table:
    bci [205, 219] => handler: 222
  Stackmap Table:
    full_frame(@132,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150]},{Object[#2]})
    full_frame(@148,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150]},{Object[#2],Object[#166]})
    same_frame(@154)
    full_frame(@184,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150],Object[#155]},{Object[#2],Uninitialized[#162],Uninitialized[#162],Object[#155],Object[#150]})
    full_frame(@185,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150],Object[#155]},{Object[#2],Uninitialized[#162],Uninitialized[#162],Object[#155],Object[#150],Object[#155]})
    full_frame(@197,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150],Object[#155]},{Object[#2],Uninitialized[#162],Uninitialized[#162],Object[#155],Object[#150],Object[#155]})
    full_frame(@199,{Object[#2],Object[#14],Object[#155],Object[#155],Integer,Integer,Object[#123],Object[#17],Object[#150],Object[#155]},{Object[#2],Uninitialized[#162],Uninitialized[#162],Object[#155],Object[#150],Object[#155],Object[#155]})
    chop_frame(@205,1)
    same_locals_1_stack_item_frame(@222,Object[#99])
    same_frame(@236)

	at net.william278.husksync.BukkitHuskSync.lambda$onEnable$5(BukkitHuskSync.java:186) ~[HuskSync-Paper-3.6-8936877.jar:?]
	at net.william278.husksync.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskSync-Paper-3.6-8936877.jar:?]
	at net.william278.husksync.HuskSync.initialize(HuskSync.java:144) ~[HuskSync-Paper-3.6-8936877.jar:?]
	... 13 more
[13:43:56] [Server thread/INFO]: [HuskSync] Disabling HuskSync v3.6-8936877
[13:43:56] [Server thread/INFO]: [net.william278.husksync.libraries.hikari.HikariDataSource] HuskSyncHikariPool - Shutdown initiated...
[13:43:56] [Server thread/INFO]: [net.william278.husksync.libraries.hikari.HikariDataSource] HuskSyncHikariPool - Shutdown completed.
[13:43:56] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling HuskSync v3.6-8936877 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.william278.husksync.redis.RedisManager.terminate()" because the return value of "net.william278.husksync.HuskSync.getRedisManager()" is null
	at net.william278.husksync.listener.EventListener.handlePluginDisable(EventListener.java:125) ~[HuskSync-Paper-3.6-8936877.jar:?]
	at net.william278.husksync.listener.BukkitEventListener.handlePluginDisable(BukkitEventListener.java:58) ~[HuskSync-Paper-3.6-8936877.jar:?]
	at net.william278.husksync.BukkitHuskSync.onDisable(BukkitHuskSync.java:227) ~[HuskSync-Paper-3.6-8936877.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:194) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

```

**Comment by WiIIiam278** [comment]
Howdy, please join Discord and verify / open a ticket for support related questions / issues! :)
