### ISSUE TITLE
Modifier is already applied on this attribute!

### ISSUE THREAD

**Issue by BAD7777** [WiIIiam278/HuskSync#327]
[HuskSync] Failed to apply data snapshot to 
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.world.entity.ai.attributes.AttributeInstance.addModifier(AttributeInstance.java:71) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.world.entity.ai.attributes.AttributeInstance.addPermanentModifier(AttributeInstance.java:91) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at org.bukkit.craftbukkit.attribute.CraftAttributeInstance.addModifier(CraftAttributeInstance.java:65) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at HuskSync-Paper-3.6.3.jar/net.william278.husksync.data.BukkitData$Attributes.lambda$applyAttribute$4(BukkitData.java:630) ~[HuskSync-Paper-3.6.3.jar:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at HuskSync-Paper-3.6.3.jar/net.william278.husksync.data.BukkitData$Attributes.applyAttribute(BukkitData.java:630) ~[HuskSync-Paper-3.6.3.jar:?]
	at HuskSync-Paper-3.6.3.jar/net.william278.husksync.data.BukkitData$Attributes.lambda$apply$3(BukkitData.java:620) ~[HuskSync-Paper-3.6.3.jar:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at HuskSync-Paper-3.6.3.jar/net.william278.husksync.data.BukkitData$Attributes.apply(BukkitData.java:620) ~[HuskSync-Paper-3.6.3.jar:?]
	at HuskSync-Paper-3.6.3.jar/net.william278.husksync.data.BukkitData.apply(BukkitData.java:62) ~[HuskSync-Paper-3.6.3.jar:?]
	at HuskSync-Paper-3.6.3.jar/net.william278.husksync.data.UserDataHolder.lambda$applySnapshot$6(UserDataHolder.java:118) ~[HuskSync-Paper-3.6.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by WiIIiam278** [comment]
Already fixed in https://github.com/WiIIiam278/HuskSync/commit/2fcd58fc184c8d033bf4f44429bf34bc361f95f9
