### ISSUE TITLE
Toast NotificationDisplaySlot logs warns in chat on send

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#350]
```[18.07 20:05:15.535] INFO: [Spawn-1] [20:05:14 WARN]: [HuskSync] Task #11450 for HuskSync v3.6.6 generated an exception
[18.07 20:05:15.536] INFO: [Spawn-1] com.google.gson.JsonParseException: No key id in MapLike[{"item":"minecraft:bell"}]
[18.07 20:05:15.536] INFO: [Spawn-1]    at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
[18.07 20:05:15.536] INFO: [Spawn-1]    at org.bukkit.craftbukkit.util.CraftMagicNumbers.loadAdvancement(CraftMagicNumbers.java:322) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
[18.07 20:05:15.536] INFO: [Spawn-1]    at HuskSync-Paper.jar/net.william278.husksync.libraries.advancement.AdvancementManager.createAll(AdvancementManager.java:98) ~[HuskSync-Paper.jar:?]
[18.07 20:05:15.536] INFO: [Spawn-1]    at HuskSync-Paper.jar/net.william278.husksync.libraries.andjam.Toast.prepareAdvancement(Toast.java:136) ~[HuskSync-Paper.jar:?]
[18.07 20:05:15.536] INFO: [Spawn-1]    at HuskSync-Paper.jar/net.william278.husksync.libraries.andjam.Toast.lambda$show$1(Toast.java:158) ~[HuskSync-Paper.jar:?]
[18.07 20:05:15.537] INFO: [Spawn-1]    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
[18.07 20:05:15.537] INFO: [Spawn-1]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
[18.07 20:05:15.537] INFO: [Spawn-1]    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1756) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
[18.07 20:05:15.537] INFO: [Spawn-1]    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
[18.07 20:05:15.537] INFO: [Spawn-1]    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1628) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
[18.07 20:05:15.537] INFO: [Spawn-1]    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1329) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
[18.07 20:05:15.537] INFO: [Spawn-1]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
[18.07 20:05:15.537] INFO: [Spawn-1]    at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by WiIIiam278** [comment]
Toast notifications have been deprecated since https://github.com/WiIIiam278/HuskSync/commit/75a2378ea8b564018678b777815bb8daeb704650
