### ISSUE TITLE
Error reflectively creating keyed attribute modifier

### ISSUE THREAD

**Issue by BAD7777** [WiIIiam278/HuskSync#351]
`[HuskSync] Error reflectively creating keyed attribute modifier
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at HuskSync-Paper-3.6.7-c949c97.jar/net.william278.husksync.data.BukkitData$Attributes.adapt(BukkitData.java:662) ~[HuskSync-Paper-3.6.7-c949c97.jar:?]
	at HuskSync-Paper-3.6.7-c949c97.jar/net.william278.husksync.data.BukkitData$Attributes.lambda$applyAttribute$2(BukkitData.java:642) ~[HuskSync-Paper-3.6.7-c949c97.jar:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at HuskSync-Paper-3.6.7-c949c97.jar/net.william278.husksync.data.BukkitData$Attributes.applyAttribute(BukkitData.java:642) ~[HuskSync-Paper-3.6.7-c949c97.jar:?]
	at HuskSync-Paper-3.6.7-c949c97.jar/net.william278.husksync.data.BukkitData$Attributes.lambda$apply$3(BukkitData.java:685) ~[HuskSync-Paper-3.6.7-c949c97.jar:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at HuskSync-Paper-3.6.7-c949c97.jar/net.william278.husksync.data.BukkitData$Attributes.apply(BukkitData.java:685) ~[HuskSync-Paper-3.6.7-c949c97.jar:?]
	at HuskSync-Paper-3.6.7-c949c97.jar/net.william278.husksync.data.BukkitData.apply(BukkitData.java:64) ~[HuskSync-Paper-3.6.7-c949c97.jar:?]
	at HuskSync-Paper-3.6.7-c949c97.jar/net.william278.husksync.data.UserDataHolder.lambda$applySnapshot$6(UserDataHolder.java:118) ~[HuskSync-Paper-3.6.7-c949c97.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1761) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Key cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.attribute.AttributeModifier.<init>(AttributeModifier.java:55) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	... 19 more`

Checking version, please wait...
Current Purpur Version: 1.21-2272-b2d1fea (MC: 1.21)
You are running the latest version
Previous: 1.20.6-2233-0d6766e (MC: 1.20.6)

**Comment by WiIIiam278** [comment]
Closing in favor of #348
