### ISSUE TITLE
Error when sync players

### ISSUE THREAD

**Issue by PeterMa9621** [WiIIiam278/HuskSync#41]
Got this error when I log in, and I can't interact with anything.
```
[12:27:54 ERROR]: [HuskSync] Failed to set data for player BiShop_Ma (java.lang.IllegalArgumentException: Health must be between 0 and 20.899999618530273, but was 22.899999618530273. (attribute base value: 22.9, player: BiShop_Ma))
[12:27:54 WARN]: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Health must be between 0 and 20.899999618530273, but was 22.899999618530273. (attribute base value: 22.9, player: BiShop_Ma)
[12:27:54 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[12:27:54 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[12:27:54 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
[12:27:54 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[12:27:54 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[12:27:54 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[12:27:54 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[12:27:54 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[12:27:54 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[12:27:54 WARN]: Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.899999618530273, but was 22.899999618530273. (attribute base value: 22.9, player: BiShop_Ma)
[12:27:54 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:110)
[12:27:54 WARN]:        at HuskSync-2.0.1.jar//net.william278.husksync.player.BukkitPlayer.lambda$setStatus$4(BukkitPlayer.java:90)
[12:27:54 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[12:27:54 WARN]:        ... 6 more
```

**Comment by WiIIiam278** [comment]
Support issue - we don't offer support via GitHub. Please join Discord for support and provide proof of purchase.
