### ISSUE TITLE
Item dupe caused by failed serialization.

### ISSUE THREAD

**Issue by nicolube** [WiIIiam278/HuskSync#434]
Well it seems that some items are not correctly upgraded when going from 1.20.2 to 1.21.1...

In this case it is an item frame (item) that is invisible when placed...
Given 1.20.2 and loaded in 1.21.1

Hiere is the exeption throwen:
```
net.william278.husksync.libraries.nbtapi.NbtApiException: [?][2.13.2]Exception while converting NMS ItemStack to NBTCompound!
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.NBTReflectionUtil.convertNMSItemtoNBTCompound(NBTReflectionUtil.java:247) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.NBTItem.convertItemtoNBT(NBTItem.java:347) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.NBTItem.convertItemArraytoNBT(NBTItem.java:384) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.NBTCompound.setItemStackArray(NBTCompound.java:623) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.BukkitSerializer$Inventory.serialize(BukkitSerializer.java:91) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.BukkitSerializer$Inventory.serialize(BukkitSerializer.java:64) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.SerializerRegistry.lambda$serializeData$5(SerializerRegistry.java:118) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.SerializerRegistry.serializeData(SerializerRegistry.java:118) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.DataSnapshot$Unpacked.lambda$serializeData$6(DataSnapshot.java:409) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.base/java.util.TreeMap$EntrySpliterator.forEachRemaining(TreeMap.java:3322) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.DataSnapshot$Unpacked.serializeData(DataSnapshot.java:407) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.DataSnapshot$Unpacked.pack(DataSnapshot.java:435) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.DataSnapshot$Builder.buildAndPack(DataSnapshot.java:802) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.data.UserDataHolder.createSnapshot(UserDataHolder.java:75) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.sync.LockstepDataSyncer.lambda$syncSaveUserData$4(LockstepDataSyncer.java:63) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: net.william278.husksync.libraries.nbtapi.NbtApiException: [?][2.13.2]Error while calling the method 'save', loaded: true, Enum: NMSITEM_SAVE_MODERN, Passed Class: class net.minecraft.world.item.ItemStack Args: [net.minecraft.core.RegistryAccess$1FrozenAccess@18a87ac8]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:399) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.NBTReflectionUtil.convertNMSItemtoNBTCompound(NBTReflectionUtil.java:240) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	... 28 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:396) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.NBTReflectionUtil.convertNMSItemtoNBTCompound(NBTReflectionUtil.java:240) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	... 28 more
Caused by: java.lang.IllegalStateException: Missing id for entity in: {Invisible:1b}
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.world.item.ItemStack.save(ItemStack.java:622) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:396) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	at HuskSync-Paper-3.7+mc.1.21.1.jar/net.william278.husksync.libraries.nbtapi.NBTReflectionUtil.convertNMSItemtoNBTCompound(NBTReflectionUtil.java:240) ~[HuskSync-Paper-3.7+mc.1.21.1.jar:?]
	... 28 more

```

**Comment by WiIIiam278** [comment]
Hi there, 

Unfortunately due to NBT changes in 1.20.6 where tags were moved to components these items are no longer valid NBT and HuskSync isn't be able upgrade them to the new format with Minecraft's DFU by default. A hook with the custom item plugin during upgrade time would be required to correct the data. Unfortunately such a hook is out of scope here; however if the custom item plugin is performing its own data upgrades it may be possible to implement a HuskSync api hook in that plugin to listen to the pre sync event and perform the upgrade appropriately in time to allow syncing to continue unimpeded.

In this case this isn't a duplication issue; it simply failed to sync the items and so locked the user in place as expected. The procedure to correct this is to delete snapshots with incompatible data using the /userdata list command and chat menu.

If you have further questions please don't hesitate to get in touch on discord.

**Comment by WiIIiam278** [comment]
Oh, alright then. Regardless though I think the issue would be with NBT-API lib rather than anything else. Could look at raising an issue there though I think that lib just defers to the DFU code
