### ISSUE TITLE
Error occurs when reading player's persistent data map

### ISSUE THREAD

**Issue by PeterMa9621** [WiIIiam278/HuskSync#46]
Sometimes, I can get this kind of error but sometimes I won't.
```
[04:48:20 WARN]: [HuskSync] Could not read bishop's persistent data map, skipping!
[04:48:20 WARN]: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: net/william278/husksync/libraries/commons/lang/ArrayUtils
[04:48:20 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[04:48:20 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[04:48:20 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[04:48:20 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[04:48:20 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[04:48:20 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[04:48:20 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[04:48:20 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[04:48:20 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[04:48:20 WARN]: Caused by: java.lang.NoClassDefFoundError: net/william278/husksync/libraries/commons/lang/ArrayUtils
[04:48:20 WARN]:        at HuskSync-2.0.1.jar//net.william278.husksync.player.BukkitPlayer.lambda$getPersistentDataContainer$40(BukkitPlayer.java:409)
[04:48:20 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[04:48:20 WARN]:        ... 6 more
[04:48:20 WARN]: Caused by: java.lang.ClassNotFoundException: net.william278.husksync.libraries.commons.lang.ArrayUtils
[04:48:20 WARN]:        ... 8 more
```

**Comment by WiIIiam278** [comment]
Already fixed in the next version, join Discord and provide proof of purchase for support.
