### ISSUE TITLE
ConcurrentModificationException when reading player persistent data maps in some cases

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskSync#81]
Stack trace below
```log
[03:25:09 WARN]: [HuskSync] Could not read KrugerRJ's persistent data map, skipping!
[03:25:09 WARN]: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[03:25:09 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[03:25:09 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1253)
[03:25:09 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2237)
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887)
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
[03:25:09 WARN]:        at HuskSync-2.2.2.jar//net.william278.husksync.player.OnlineUser.lambda$getUserData$3(OnlineUser.java:358)
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[03:25:09 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[03:25:09 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[03:25:09 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[03:25:09 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[03:25:09 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[03:25:09 WARN]: Caused by: java.util.ConcurrentModificationException
[03:25:09 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
[03:25:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.persistence.CraftPersistentDataTypeRegistry.isInstanceOf(CraftPersistentDataTypeRegistry.java:231)
[03:25:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.persistence.CraftPersistentDataContainer.has(CraftPersistentDataContainer.java:54)
[03:25:09 WARN]:        at HuskSync-2.2.2.jar//net.william278.husksync.player.BukkitPlayer.lambda$getPersistentDataContainer$40(BukkitPlayer.java:462)
[03:25:09 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[03:25:09 WARN]:        ... 14 more```

**Comment by WiIIiam278** [comment]
_Should_ be fixed in 1d7f6a8d8b6b7155f967aa0f8e14f5003b1624f9
